name: "danger-textlint-actions"
description: "This GitHub Action submits textlint review comments if there are violations."
branding:
  icon: "check-circle"
  color: "gray-dark"
runs:
  using: "docker"
  image: "Dockerfile"
